# Generated by Django 5.0.6 on 2024-08-29 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MifareClassicCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=8, unique=True)),
                ('type', models.CharField(choices=[('EASY_CARD', '悠遊卡'), ('I_PASS', '一卡通'), ('HAPPY_CASH', '有錢卡')], max_length=10)),
                ('number', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=50)),
                ('is_kuokuang_card', models.BooleanField(verbose_name='這是國光回數票悠遊卡')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MifareClassicCardSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('key_a', models.CharField(blank=True, max_length=12)),
                ('key_b', models.CharField(blank=True, max_length=12)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.mifareclassiccard')),
            ],
        ),
    ]
